name: mentorai
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  provider: ^6.0.1
  agora_rtc_engine: ^4.0.7
  permission_handler: ^8.2.5
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
    - images/
    - google_fonts/
    - .env
